version: "3.8"

services:
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium-backend:
    image: healenium/hlm-backend:3.4.7
    container_name: healenium-backend
    ports:
      - "7878:7878"
    environment:
      - CAPTURE_DOM=true
      - FORCE_DOM_CAPTURE=true
      - HEALING_REQUIRE_METADATA=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/healenium
      - SPRING_DATASOURCE_USERNAME=healenium_user
      - SPRING_DATASOURCE_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - HLM_LOG_LEVEL=DEBUG
    depends_on:
      - postgres-db
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    ports:
      - "8000:8000"
    networks:
      - healenium

networks:
  healenium: