version: "3.8"

services:

  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium-backend:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium-backend
    ports:
      - "7878:7878"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/healenium
      SPRING_DATASOURCE_USERNAME: healenium_user
      SPRING_DATASOURCE_PASSWORD: YDk2nmNs4s9aCP6K
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      KEY_SELECTOR_URL: "false"
      COLLECT_METRICS: "true"
      FIND_ELEMENTS_AUTO_HEALING: "true"
      HLM_LOG_LEVEL: info
    depends_on:
      - postgres-db
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - healenium

  selenium-standalone:
    image: selenium/standalone-chrome:latest
    container_name: selenium-standalone
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - healenium

  healenium-proxy:
    image: healenium/hlm-proxy:2.1.7
    container_name: healenium-proxy
    ports:
      - "4455:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/healenium
      SPRING_DATASOURCE_USERNAME: healenium_user
      SPRING_DATASOURCE_PASSWORD: YDk2nmNs4s9aCP6K
      HEALENIUM_SERVICE: http://healenium-backend:7878
      IMITATE_SERVICE: http://selector-imitator:8000
      SELENIUM_SERVER_URL: http://selenium-standalone:4444/wd/hub
    depends_on:
      - postgres-db
      - healenium-backend
      - selector-imitator
      - selenium-standalone
    networks:
      - healenium

networks:
  healenium:
